[package]
name = "vntyper-gtk"
version = "0.1.0"
authors = ["Do Duy <doduycm@gmail.com>"]

[dependencies]
gdk = "0.5.3"
vntyper = { git = "https://github.com/vntyper/vntyper.git" }

[dependencies.gtk]
version = "0.1.3"
features = ["v3_16"]
